#!/bin/sh

# 挂载必要的文件系统
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev

# 打印日志
echo "Hello 64-bit ARM Linux"

# 显示开机消耗时间
echo "This boot took $(cut -d' ' -f1 /proc/uptime) seconds"

# 启动一个shell
exec /bin/sh
